# Generated by Django 2.2.4 on 2019-08-25 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='birthdate'),
            preserve_default=False,
        ),
    ]
