# Generated by Django 2.2.7 on 2019-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190825_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=15, null=True, verbose_name='gender'),
        ),
    ]
